version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M1e2h3d4i5
      MYSQL_DATABASE: the_maze_db
      MYSQL_PASSWORD: M1e2h3d4i5
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
